### ISSUE TITLE
Can't deploy the project on NuxtHub

### ISSUE THREAD

**Issue by daisnkzy** [SupersaasHQ/lemonrepo#5]
when I clone the template on nuxthub and deploy it to cloudflare, it failed and showed the errors:

`
20:18:11.691 1: import { stdin, stdout } from "node:process";    

20:18:11.691             ^
20:18:11.691 2: import f from "node:readline";
20:18:11.691 3: import { WriteStream } from "node:tty";
20:18:11.693 [error] node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-CUmb8XXS.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by "node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-CUmb8XXS.js".
20:18:11.693   at getRollupError (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:395:41)
20:18:11.693   at error (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/parseAst.js:391:42)
20:18:11.693   at Module.error (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:15535:16)
20:18:11.694   at Module.traceVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:15984:29)
20:18:11.694   at ModuleScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:13770:39)
20:18:11.694   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
20:18:11.694   at ClassBodyScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
20:18:11.694   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
20:18:11.694   at ChildScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38)
20:18:11.694   at FunctionScope.findVariable (node_modules/.pnpm/rollup@4.24.0/node_modules/rollup/dist/es/shared/node-entry.js:5252:38) 
20:18:11.694 
20:18:11.694 [error] node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-CUmb8XXS.js (1:9): "stdin" is not exported by "node_modules/.pnpm/unenv@1.10.0/node_modules/unenv/runtime/node/process/index.mjs", imported by "node_modules/.cache/nuxt/.nuxt/dist/server/_nuxt/prompt-CUmb8XXS.js".
20:18:11.766 Failed: Error while executing user command. Exited with error code: 1
20:18:11.776 Failed: build command exited with code: 1
20:18:15.986 Failed: error occurred while running build command
`

**Comment by daisnkzy** [comment]
update the nuxt/core and wrangler package can solve this problem
